### ISSUE TITLE
성능테스트, 동시성 이슈 해결

### ISSUE THREAD

**Issue by Jungsu-lilly** [Jungsu-lilly/First-Come-First-Served-CouponSystem#1]
## Description 📝
* 대량의 트래픽이 몰리는 상황을 가정해 성능 테스트를 수행하고, 그에 따른 동시성 이슈 등의 문제를 해결합니다.
<br> 

## TODO ✅
- [x] 성능 테스트 수행 (대량의 트래픽이 들어오는 상황 가정)
- [x] 동시성 이슈 파악
- [x] Redis를 통한 동시성 이슈 해결
