### ISSUE TITLE
Redis 쿠폰 발급 서버 구현

### ISSUE THREAD

**Issue by Jungsu-lilly** [Jungsu-lilly/First-Come-First-Served-CouponSystem#3]
## Description 📝
* Redis를 사용해 API 서버를 구현합니다.
* 비동기 방식으로 쿠폰발급을 처리하는 아키텍처를 구현합니다.

<br>

## TODO ✅

- [x] Sorted set 을 통한 구현
- [x] Set을 통한 구현
- [ ] 레디스 캐시 적용
